export const START_FETCHING_ALBUMS = 'ALBUMS/START_FETCHING'
export const FETCH_ALBUMS_SUCCEDDED = 'ALBUMS/FETCH_SUCCEDDED'
export const FETCH_ALBUMS_FAILED = 'ALBUMS/FETCH_FAILED'

export const START_FETCHING_ALBUM_PHOTOS = 'ALBUM/START_FETCHING_PHOTOS'
export const FETCH_ALBUM_PHOTOS_SUCCEDDED = 'ALBUM/FETCH_PHOTOS_SUCCEDDED'
export const FETCH_ALBUM_PHOTOS_FAILED = 'ALBUM/FETCH_PHOTOS_FAILED'


export const LOAD_MORE_ALBUMS = 'ALBUMS/LOAD_MORE'