
export enum TYPES {
  START_FETCHING_ALBUMS = 'ALBUMS/START_FETCHING',
  FETCH_ALBUMS_SUCCEDDED = 'ALBUMS/FETCH_SUCCEDDED',
  FETCH_ALBUMS_FAILED = 'ALBUMS/FETCH_FAILED',
  START_FETCHING_ALBUM_PHOTOS = 'ALBUM/START_FETCHING_PHOTOS',
  FETCH_ALBUM_PHOTOS_SUCCEDDED = 'ALBUM/FETCH_PHOTOS_SUCCEDDED',
  FETCH_ALBUM_PHOTOS_FAILED = 'ALBUM/FETCH_PHOTOS_FAILED',
  LOAD_MORE_ALBUMS = 'ALBUMS/LOAD_MORE'
}